#!/usr/bin/env python
"""fmdw MCP server — expose the fmdw convert+QA harness as MCP tools.

Wraps fmdw_convert_qa_phase1.sh (synchronous harness: convert + deterministic
QA x3 + report generation, git ab9e8d0+) behind an async job model over MCP
stdio transport (FastMCP):

  * start_convert  — launch the harness detached (nohup-equivalent), return a
                     job_id immediately (never blocks on the conversion)
  * job_status     — poll job state (running / succeeded / failed), harness
                     exit code, PHASE1-STATUS line, output paths
  * get_qa_report  — return the final goose_qa_report.md content

Design notes:
  - Job metadata is persisted under output/_mcp_jobs/<job_id>.json so that
    job_status / get_qa_report work across MCP server restarts.
  - Concurrent-run protection is delegated to the harness itself (pgrep
    guard -> exit code 3 = PROCESS_CONFLICT); we report that honestly.
  - No secrets are read or emitted by this server.

Run: .venv/bin/python fmdw_mcp_server.py     (stdio)
"""
from __future__ import annotations

import json
import os
import shlex
import signal
import subprocess
import time
import uuid
from pathlib import Path

from fastmcp import FastMCP

REPO = Path(__file__).resolve().parent
HARNESS = REPO / "fmdw_convert_qa_phase1.sh"
INPUT_PDF_DIR = REPO / "input" / "pdf"
JOBS_DIR = REPO / "output" / "_mcp_jobs"

# fmdw_convert_qa_phase1.sh exit-code contract
RC_MEANING = {
    0: "PASS_CLEAN",
    1: "PASS_WITH_FLAGS",
    2: "USAGE_ERROR",
    3: "PROCESS_CONFLICT",  # harness pgrep guard: another convert is running
    4: "CONVERT_FAILED",
}

VISION_CHECK_MAP = {
    "auto": "on_low_confidence",  # harness default
    "on_low_confidence": "on_low_confidence",
    "always": "always",
    "off": "off",
}

ALLOWED_DOMAINS = {"datasheet", "schematic", "reference", "design_doc", "source_code", "general"}

mcp = FastMCP("fmdw")


# ---------------------------------------------------------------- helpers
def _resolve_input_pdf(input_pdf: str) -> Path:
    """Validate the input path: either a name under input/pdf/ (or relative
    to the repo), or an absolute path that exists. Must be a .pdf file."""
    raw = Path(input_pdf).expanduser()
    if raw.is_absolute():
        p = raw.resolve()
    else:
        p = (INPUT_PDF_DIR / input_pdf).resolve()
        if not p.is_file():
            p = (REPO / input_pdf).resolve()
    if not p.is_file():
        raise ValueError(
            f"input_pdf not found: {input_pdf!r} "
            f"(looked under {INPUT_PDF_DIR} and as absolute/repo-relative path)"
        )
    if p.suffix.lower() != ".pdf":
        raise ValueError(f"input_pdf must be a .pdf file, got: {p.name}")
    return p


def _meta_path(job_id: str) -> Path:
    # job_id is generated by us: reject anything that could traverse paths
    if not job_id or any(c in job_id for c in "/\\") or job_id.startswith("."):
        raise ValueError(f"invalid job_id: {job_id!r}")
    return JOBS_DIR / f"{job_id}.json"


def _load_meta(job_id: str) -> dict:
    mp = _meta_path(job_id)
    if not mp.is_file():
        raise ValueError(f"unknown job_id: {job_id!r} (no metadata at {mp})")
    return json.loads(mp.read_text(encoding="utf-8"))


def _pid_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
        return True
    except ProcessLookupError:
        return False
    except PermissionError:
        return True


def _phase1_status_line(log_path: Path) -> str | None:
    if not log_path.is_file():
        return None
    status = None
    try:
        for line in log_path.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith("PHASE1-STATUS:"):
                status = line.strip()
    except OSError:
        return None
    return status


def _tail(log_path: Path, n: int = 15) -> list[str]:
    if not log_path.is_file():
        return []
    lines = log_path.read_text(encoding="utf-8", errors="replace").splitlines()
    return lines[-n:]


# ------------------------------------------------------------------ tools
@mcp.tool
def start_convert(
    input_pdf: str,
    domain: str = "datasheet",
    vision_check: str = "auto",
) -> dict:
    """Start an fmdw PDF -> Markdown conversion + QA job (non-blocking).

    Launches fmdw_convert_qa_phase1.sh detached and returns a job_id
    immediately. Poll with job_status(job_id); fetch the QA report with
    get_qa_report(job_id) once the job has finished.

    Args:
        input_pdf: PDF file name under input/pdf/ (e.g. "DM_p0018-0024.pdf")
            or an absolute path to an existing PDF.
        domain: fmdw domain (datasheet | schematic | reference | design_doc |
            source_code | general). Default: datasheet.
        vision_check: auto (= harness default on_low_confidence) | always | off.
    """
    pdf = _resolve_input_pdf(input_pdf)
    if domain not in ALLOWED_DOMAINS:
        raise ValueError(f"unknown domain {domain!r}; allowed: {sorted(ALLOWED_DOMAINS)}")
    vc = VISION_CHECK_MAP.get(vision_check)
    if vc is None:
        raise ValueError(
            f"unknown vision_check {vision_check!r}; allowed: {sorted(VISION_CHECK_MAP)}"
        )

    ts = time.strftime("%Y%m%d_%H%M%S")
    job_id = f"{ts}_{pdf.stem}_{uuid.uuid4().hex[:6]}"
    outsub = f"mcp_{job_id}"
    JOBS_DIR.mkdir(parents=True, exist_ok=True)
    job_log = JOBS_DIR / f"{job_id}.log"
    rc_file = JOBS_DIR / f"{job_id}.rc"

    cmd = (
        f"/bin/bash {shlex.quote(str(HARNESS))} {shlex.quote(str(pdf))} "
        f"{shlex.quote(domain)} {shlex.quote(outsub)} full {shlex.quote(vc)} "
        f"> {shlex.quote(str(job_log))} 2>&1; "
        f"echo $? > {shlex.quote(str(rc_file))}"
    )
    proc = subprocess.Popen(
        ["/bin/bash", "-c", cmd],
        cwd=str(REPO),
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,  # detach: survives MCP server exit
    )

    outdir = REPO / "output" / outsub
    meta = {
        "job_id": job_id,
        "pid": proc.pid,
        "input_pdf": str(pdf),
        "domain": domain,
        "vision_check": vc,
        "output_subdir": outsub,
        "output_dir": str(outdir),
        "converted_md": str(outdir / f"{pdf.stem}.md"),
        "qa_report": str(outdir / "goose_qa_report.md"),
        "phase1_summary": str(outdir / "phase1_summary.json"),
        "job_log": str(job_log),
        "rc_file": str(rc_file),
        "started_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
    }
    _meta_path(job_id).write_text(
        json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    return {
        "job_id": job_id,
        "state": "running",
        "message": "conversion started in background; poll with job_status(job_id)",
        "input_pdf": str(pdf),
        "domain": domain,
        "vision_check": vc,
        "output_dir": str(outdir),
    }


def _job_status_impl(job_id: str) -> dict:
    """Shared status logic (also used by get_qa_report)."""
    meta = _load_meta(job_id)
    rc_file = Path(meta["rc_file"])
    job_log = Path(meta["job_log"])
    out: dict = {
        "job_id": job_id,
        "started_at": meta.get("started_at"),
        "input_pdf": meta.get("input_pdf"),
        "domain": meta.get("domain"),
        "output_dir": meta.get("output_dir"),
    }

    if rc_file.is_file():
        try:
            rc = int(rc_file.read_text().strip() or "-1")
        except ValueError:
            rc = -1
        out["exit_code"] = rc
        out["exit_meaning"] = RC_MEANING.get(rc, f"UNKNOWN_RC_{rc}")
        out["state"] = "succeeded" if rc in (0, 1) else "failed"
        out["phase1_status"] = _phase1_status_line(job_log)
        md = Path(meta["converted_md"])
        rep = Path(meta["qa_report"])
        out["converted_md"] = str(md) if md.is_file() else None
        out["qa_report"] = str(rep) if rep.is_file() else None
        summ = Path(meta["phase1_summary"])
        out["phase1_summary"] = str(summ) if summ.is_file() else None
        if out["state"] == "failed":
            out["log_tail"] = _tail(job_log)
    elif _pid_alive(int(meta["pid"])):
        out["state"] = "running"
        out["phase1_status"] = None
        out["log_tail"] = _tail(job_log, 3)
    else:
        out["state"] = "failed"
        out["exit_code"] = None
        out["exit_meaning"] = "ORPHANED (process gone, no exit code recorded)"
        out["phase1_status"] = _phase1_status_line(job_log)
        out["log_tail"] = _tail(job_log)
    return out


@mcp.tool
def job_status(job_id: str) -> dict:
    """Return the current state of a conversion job started by start_convert.

    States:
        running    — harness still executing
        succeeded  — exit code 0 (PASS_CLEAN) or 1 (PASS_WITH_FLAGS)
        failed     — exit code 2 (usage) / 3 (process conflict) / 4 (convert
                     failure), or the process disappeared without writing rc
    Includes the final "PHASE1-STATUS: ..." line and output paths.
    """
    return _job_status_impl(job_id)


@mcp.tool
def get_qa_report(job_id: str) -> dict:
    """Return the goose_qa_report.md content for a finished job.

    If the job is still running (or failed before producing a report),
    returns state info instead of the report body.
    """
    meta = _load_meta(job_id)
    status = _job_status_impl(job_id)  # reuse the status logic
    rep = Path(meta["qa_report"])
    if status["state"] == "running":
        return {"job_id": job_id, "state": "running", "report": None,
                "message": "job still running; poll job_status first"}
    if not rep.is_file():
        return {"job_id": job_id, "state": status["state"], "report": None,
                "message": f"no QA report at {rep} "
                           f"(exit: {status.get('exit_meaning')})",
                "log_tail": status.get("log_tail")}
    return {
        "job_id": job_id,
        "state": status["state"],
        "exit_meaning": status.get("exit_meaning"),
        "phase1_status": status.get("phase1_status"),
        "report_path": str(rep),
        "report": rep.read_text(encoding="utf-8", errors="replace"),
    }


if __name__ == "__main__":
    mcp.run()  # stdio transport (default)
